name: ${project.name}
version: ${project.version}

main: me.remag501.adventure.AdventurePlugin
api-version: '1.21'

commands:
  adventure:
    description: Teleport to the current adventure world
    usage: /adventure
  chance:
    description: Run one of multiple commands using weighted chances
    usage: /chance <weight%"command",weight%"command",...>
    permission: adventure.chance

permissions:
  adventure.chance:
    description: Allows use of /chance
    default: op

depend:
  - BGSCore
  - Multiverse-Core
  - BetterRTP
  - PlaceholderAPI

softdepend:
  - Oraxen

